/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import classes.*;
import classes.Controllers.SetupController;

public class App {

    public static void main(String[] args) {
        SetupController setupController = new SetupController();
        setupController.gameSetup();

        GameEngine gameEngine = new GameEngine(setupController.getTrack(), setupController.getPlayers());
        gameEngine.startRace();
    }
}
